[tool.poetry]
name = "chain-bot"
version = "0.1.0"
description = ""
authors = ["Oleg2Pi <polikarpovoleg115@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
